-- This initial PostgreSQL migration is generated from the current Prisma data model.
CREATE TABLE "User" ("id" TEXT NOT NULL, "phone" TEXT NOT NULL, "email" TEXT, "name" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'MEMBER', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Tontine" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "type" TEXT NOT NULL DEFAULT 'ROTATIVE', "currency" TEXT NOT NULL DEFAULT 'XOF', "contributionAmount" DOUBLE PRECISION NOT NULL, "frequency" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'DRAFT', "maxMembers" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdById" TEXT NOT NULL, CONSTRAINT "Tontine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TontineRule" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "key" TEXT NOT NULL, "value" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'STRING', CONSTRAINT "TontineRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TontineMember" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'MEMBER', "status" TEXT NOT NULL DEFAULT 'ACTIVE', "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "leftAt" TIMESTAMP(3), "payoutOrder" INTEGER, "isPayoutReceived" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "TontineMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TontineCycle" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "name" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'UPCOMING', "beneficiaryMemberId" TEXT, "potAmount" DOUBLE PRECISION, "potReceived" DOUBLE PRECISION DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TontineCycle_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Contribution" ("id" TEXT NOT NULL, "cycleId" TEXT NOT NULL, "memberId" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "method" TEXT NOT NULL DEFAULT 'MANUAL', "providerRef" TEXT, "declaredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "confirmedAt" TIMESTAMP(3), "confirmedById" TEXT, "lateFee" DOUBLE PRECISION NOT NULL DEFAULT 0, "penaltyApplied" BOOLEAN NOT NULL DEFAULT false, "notes" TEXT, CONSTRAINT "Contribution_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payout" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "cycleId" TEXT NOT NULL, "memberId" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "method" TEXT NOT NULL DEFAULT 'MANUAL', "providerRef" TEXT, "initiatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "failureReason" TEXT, CONSTRAINT "Payout_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentProvider" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "config" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "apiKeyRef" TEXT, "webhookSecretRef" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentProvider_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentTransaction" ("id" TEXT NOT NULL, "providerId" TEXT NOT NULL, "providerRef" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "currency" TEXT NOT NULL DEFAULT 'XOF', "status" TEXT NOT NULL, "direction" TEXT NOT NULL, "metadata" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Vote" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "question" TEXT NOT NULL, "options" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "quorum" INTEGER NOT NULL DEFAULT 0, "eligibleVoterIds" TEXT NOT NULL, "result" TEXT, "openedAt" TIMESTAMP(3), "closedAt" TIMESTAMP(3), "createdById" TEXT NOT NULL, CONSTRAINT "Vote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VoteBallot" ("id" TEXT NOT NULL, "voteId" TEXT NOT NULL, "memberId" TEXT NOT NULL, "choice" TEXT NOT NULL, "votedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "VoteBallot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Dispute" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "cycleId" TEXT, "contributionId" TEXT, "type" TEXT NOT NULL, "description" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "openedById" TEXT NOT NULL, "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), "resolvedById" TEXT, "decision" TEXT, CONSTRAINT "Dispute_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DisputeEvidence" ("id" TEXT NOT NULL, "disputeId" TEXT NOT NULL, "url" TEXT NOT NULL, "description" TEXT, "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DisputeEvidence_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TrustProfile" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "cyclesCompleted" INTEGER NOT NULL DEFAULT 0, "paymentsOnTime" INTEGER NOT NULL DEFAULT 0, "paymentsLate" INTEGER NOT NULL DEFAULT 0, "disputesResolved" INTEGER NOT NULL DEFAULT 0, "disputesUnresolved" INTEGER NOT NULL DEFAULT 0, "memberSince" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "score" INTEGER NOT NULL DEFAULT 50, CONSTRAINT "TrustProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "actorId" TEXT, "actorRole" TEXT NOT NULL, "action" TEXT NOT NULL, "resource" TEXT NOT NULL, "resourceId" TEXT, "metadata" TEXT NOT NULL, "ipAddress" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AIConversation" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tontineId" TEXT, "messages" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AIConversation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AIInsight" ("id" TEXT NOT NULL, "tontineId" TEXT NOT NULL, "type" TEXT NOT NULL, "data" TEXT NOT NULL, "priority" TEXT NOT NULL DEFAULT 'LOW', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AIInsight_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "channel" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "data" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "sentAt" TIMESTAMP(3), "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RefreshToken" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "token" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "token" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "ipAddress" TEXT NOT NULL, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_phone_idx" ON "User"("phone");
CREATE INDEX "User_email_idx" ON "User"("email");
CREATE INDEX "User_role_idx" ON "User"("role");
CREATE INDEX "User_status_idx" ON "User"("status");
CREATE INDEX "Tontine_createdById_idx" ON "Tontine"("createdById");
CREATE INDEX "Tontine_status_idx" ON "Tontine"("status");
CREATE INDEX "Tontine_type_idx" ON "Tontine"("type");
CREATE INDEX "Tontine_startDate_idx" ON "Tontine"("startDate");
CREATE INDEX "TontineRule_tontineId_idx" ON "TontineRule"("tontineId");
CREATE INDEX "TontineRule_tontineId_key_idx" ON "TontineRule"("tontineId", "key");
CREATE INDEX "TontineMember_tontineId_idx" ON "TontineMember"("tontineId");
CREATE INDEX "TontineMember_userId_idx" ON "TontineMember"("userId");
CREATE INDEX "TontineMember_tontineId_userId_idx" ON "TontineMember"("tontineId", "userId");
CREATE INDEX "TontineMember_tontineId_status_idx" ON "TontineMember"("tontineId", "status");
CREATE INDEX "TontineCycle_tontineId_idx" ON "TontineCycle"("tontineId");
CREATE INDEX "TontineCycle_tontineId_sequence_idx" ON "TontineCycle"("tontineId", "sequence");
CREATE INDEX "TontineCycle_status_idx" ON "TontineCycle"("status");
CREATE INDEX "TontineCycle_startDate_idx" ON "TontineCycle"("startDate");
CREATE INDEX "Contribution_cycleId_idx" ON "Contribution"("cycleId");
CREATE INDEX "Contribution_memberId_idx" ON "Contribution"("memberId");
CREATE INDEX "Contribution_cycleId_memberId_idx" ON "Contribution"("cycleId", "memberId");
CREATE INDEX "Contribution_status_idx" ON "Contribution"("status");
CREATE INDEX "Contribution_declaredAt_idx" ON "Contribution"("declaredAt");
CREATE INDEX "Payout_tontineId_idx" ON "Payout"("tontineId");
CREATE INDEX "Payout_cycleId_idx" ON "Payout"("cycleId");
CREATE INDEX "Payout_memberId_idx" ON "Payout"("memberId");
CREATE INDEX "Payout_status_idx" ON "Payout"("status");
CREATE INDEX "Payout_initiatedAt_idx" ON "Payout"("initiatedAt");
CREATE UNIQUE INDEX "PaymentProvider_name_key" ON "PaymentProvider"("name");
CREATE INDEX "PaymentProvider_type_idx" ON "PaymentProvider"("type");
CREATE INDEX "PaymentProvider_isActive_idx" ON "PaymentProvider"("isActive");
CREATE INDEX "PaymentTransaction_providerId_idx" ON "PaymentTransaction"("providerId");
CREATE INDEX "PaymentTransaction_providerRef_idx" ON "PaymentTransaction"("providerRef");
CREATE INDEX "PaymentTransaction_status_idx" ON "PaymentTransaction"("status");
CREATE INDEX "PaymentTransaction_createdAt_idx" ON "PaymentTransaction"("createdAt");
CREATE INDEX "Vote_tontineId_idx" ON "Vote"("tontineId");
CREATE INDEX "Vote_status_idx" ON "Vote"("status");
CREATE INDEX "Vote_openedAt_idx" ON "Vote"("openedAt");
CREATE INDEX "VoteBallot_voteId_idx" ON "VoteBallot"("voteId");
CREATE INDEX "VoteBallot_memberId_idx" ON "VoteBallot"("memberId");
CREATE UNIQUE INDEX "VoteBallot_voteId_memberId_key" ON "VoteBallot"("voteId", "memberId");
CREATE INDEX "Dispute_tontineId_idx" ON "Dispute"("tontineId");
CREATE INDEX "Dispute_cycleId_idx" ON "Dispute"("cycleId");
CREATE INDEX "Dispute_status_idx" ON "Dispute"("status");
CREATE INDEX "Dispute_openedAt_idx" ON "Dispute"("openedAt");
CREATE INDEX "DisputeEvidence_disputeId_idx" ON "DisputeEvidence"("disputeId");
CREATE UNIQUE INDEX "TrustProfile_userId_key" ON "TrustProfile"("userId");
CREATE INDEX "TrustProfile_score_idx" ON "TrustProfile"("score");
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");
CREATE INDEX "AuditLog_resource_idx" ON "AuditLog"("resource");
CREATE INDEX "AuditLog_resourceId_idx" ON "AuditLog"("resourceId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");
CREATE INDEX "AIConversation_userId_idx" ON "AIConversation"("userId");
CREATE INDEX "AIConversation_tontineId_idx" ON "AIConversation"("tontineId");
CREATE INDEX "AIConversation_createdAt_idx" ON "AIConversation"("createdAt");
CREATE INDEX "AIInsight_tontineId_idx" ON "AIInsight"("tontineId");
CREATE INDEX "AIInsight_priority_idx" ON "AIInsight"("priority");
CREATE INDEX "AIInsight_createdAt_idx" ON "AIInsight"("createdAt");
CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");
CREATE INDEX "Notification_status_idx" ON "Notification"("status");
CREATE INDEX "Notification_channel_idx" ON "Notification"("channel");
CREATE INDEX "Notification_createdAt_idx" ON "Notification"("createdAt");
CREATE UNIQUE INDEX "RefreshToken_token_key" ON "RefreshToken"("token");
CREATE INDEX "RefreshToken_userId_idx" ON "RefreshToken"("userId");
CREATE INDEX "RefreshToken_expiresAt_idx" ON "RefreshToken"("expiresAt");
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");

ALTER TABLE "Tontine" ADD CONSTRAINT "Tontine_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TontineRule" ADD CONSTRAINT "TontineRule_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TontineMember" ADD CONSTRAINT "TontineMember_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TontineMember" ADD CONSTRAINT "TontineMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TontineCycle" ADD CONSTRAINT "TontineCycle_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TontineCycle" ADD CONSTRAINT "TontineCycle_beneficiaryMemberId_fkey" FOREIGN KEY ("beneficiaryMemberId") REFERENCES "TontineMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Contribution" ADD CONSTRAINT "Contribution_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "TontineCycle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Contribution" ADD CONSTRAINT "Contribution_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "TontineMember"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Contribution" ADD CONSTRAINT "Contribution_confirmedById_fkey" FOREIGN KEY ("confirmedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "TontineCycle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "TontineMember"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentTransaction" ADD CONSTRAINT "PaymentTransaction_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "PaymentProvider"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "VoteBallot" ADD CONSTRAINT "VoteBallot_voteId_fkey" FOREIGN KEY ("voteId") REFERENCES "Vote"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VoteBallot" ADD CONSTRAINT "VoteBallot_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "TontineMember"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_openedById_fkey" FOREIGN KEY ("openedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_contributionId_fkey" FOREIGN KEY ("contributionId") REFERENCES "Contribution"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DisputeEvidence" ADD CONSTRAINT "DisputeEvidence_disputeId_fkey" FOREIGN KEY ("disputeId") REFERENCES "Dispute"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TrustProfile" ADD CONSTRAINT "TrustProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AIConversation" ADD CONSTRAINT "AIConversation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AIConversation" ADD CONSTRAINT "AIConversation_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AIInsight" ADD CONSTRAINT "AIInsight_tontineId_fkey" FOREIGN KEY ("tontineId") REFERENCES "Tontine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;